export const DIRECTION_UP = 1
export const DIRECTION_RIGHT = 2
export const DIRECTION_DOWN = 4
export const DIRECTION_LEFT = 8
export const _DIRECTION_ANY = DIRECTION_UP | DIRECTION_RIGHT | DIRECTION_DOWN | DIRECTION_LEFT
export const ACTION_FIRE = 16